### ISSUE TITLE
Model loading from gluon zoo not working for many models

### ISSUE THREAD

**Issue by masahi** [dmlc/nnvm#203] opened 2017-10-28 00:04 UTC
I'm testing gluon model loading into nnvm [with this script](https://gist.github.com/masahi/1b7bf02da8034cabf5ebd603b18e43d6).

So far, I confirmed that "alexnet", "resnet18_v1", "resnet50_v1" worked.
But other models are not working for me.

My mxnet version:
```
In [1]: import mxnet

In [2]: mxnet.__version__
Out[2]: '0.11.0'
```

With vgg16, I got this error:
```
$ python test_gluon_model.py 
x (1, 3, 224, 224)
[09:02:16] /home/masa/project/dev/tvm/dmlc-core/include/dmlc/logging.h:308: [09:02:16] src/top/nn/nn.cc:44: Operator dense(use_bias=True, units=4096, name=dense0) expects weight's shape to be [4096,7], but got [4096,25088].
```

with resnet101_v1:
```
RecursionError: maximum recursion depth exceeded in comparison
```

with inceptionv3:
```
ValueError: There are multiple outputs with name "inception30_E1_concat0_output"
```

**Comment by zhreshold** [comment] 2017-10-28 23:06
Vgg should be fixed already, I will investigate others.

**Comment by zhreshold** [comment] 2017-10-30 20:37
inceptionv3 is not working because the workload is (1, 3, 299, 299) which seems to cause trouble in TVM schedules.
The resnet problem is not reproducing on my machine but I could confirm it is a potential problem if the stack limit is small in some machines.

**Comment by masahi** [comment] 2017-11-09 00:27
@zhreshold I confirmed that vgg16 works now.

resnet101_v1 also worked if I add something like
```
import sys
sys.setrecursionlimit(10000)
```

**Closed** 2017-11-14 07:29 UTC
